spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:explorewithme
    username: explorewithme
    password: explorewithme
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
feign:
  okhttp:
    enabled: true