server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/explorewithme
    username: explorewithme
    password: explorewithme
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  sql.init.mode: always

feign:
  okhttp:
    enabled: true

logging.level.org.springframework:
  web.client.RestTemplate: DEBUG
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: DEBUG

logging.level.ru.practicum.explorewithme: TRACE